sudo: required
services:
  - docker
before_install:
  - docker build -t hazelnut95/react-test -f ./client/Dockerfile.dev ./client/
script:
  - docker run -e CI=true hazelnut95/react-test npm test

after_sucess:
  - docker build -t hazelnut95/multi-client ./client
  - docker build -t hazelnut95/multi-nginx ./nginx
  - docker build -t hazelnut95/multi-server ./server
  - docker build -t hazelnut95/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push hazelnut95/multi-client
  - docker push hazelnut95/multi-nginx
  - docker push hazelnut95/multi-server
  - docker push hazelnut95/multi-worker
deploy:
  provider: elasticbeanstalk
  region: asia-pacfic-1a
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstlak-us-west-1-306477627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
