sudo: required
services:
  - docker
before_install:
  - docker build -t hazelnut95/react-test -f ./client/Dockerfile.dev ./client/
script:
  - docker run hazelnut95/react-test npm test -- --coverage

after_sucess:
  - docker build -t hazelnut95/multi-client ./client
  - docker build -t hazelnut95/multi-nginx ./nginx
  - docker build -t hazelnut95/multi-server ./server
  - docker build -t hazelnut95/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push hazelnut95/multi-client
  - docker push hazelnut95/multi-nginx
  - docker push hazelnut95/multi-server
  - docker push hazelnut95/multi-worker